services:
    crizzo.maxwidthswitch.listener:
        class: crizzo\maxwidthswitch\event\listener
        arguments:
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }
